# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'restore_alert.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RestoreAlert(object):
    def setupUi(self, RestoreAlert):
        RestoreAlert.setObjectName("RestoreAlert")
        RestoreAlert.setFixedSize(426, 129)
        RestoreAlert.setFocusPolicy(QtCore.Qt.NoFocus)
        RestoreAlert.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        RestoreAlert.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox = QtWidgets.QDialogButtonBox(RestoreAlert)
        self.buttonBox.setGeometry(QtCore.QRect(30, 90, 371, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setFocusPolicy(QtCore.Qt.TabFocus)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.mainLabel = QtWidgets.QLabel(RestoreAlert)
        self.mainLabel.setGeometry(QtCore.QRect(20, 10, 381, 61))
        self.mainLabel.setLineWidth(1)
        self.mainLabel.setTextFormat(QtCore.Qt.AutoText)
        self.mainLabel.setScaledContents(True)
        self.mainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mainLabel.setWordWrap(True)
        self.mainLabel.setObjectName("mainLabel")

        self.retranslateUi(RestoreAlert)
        QtCore.QMetaObject.connectSlotsByName(RestoreAlert)

    def retranslateUi(self, RestoreAlert):
        _translate = QtCore.QCoreApplication.translate
        RestoreAlert.setWindowTitle(_translate("RestoreAlert", "Restore Defaults"))
        self.mainLabel.setText(_translate("RestoreAlert", "Are you sure you want to restore setting to deafult?\n"
"\n"
"You will lose all preferences made."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RestoreAlert = QtWidgets.QDialog()
    ui = Ui_RestoreAlert()
    ui.setupUi(RestoreAlert)
    RestoreAlert.show()
    sys.exit(app.exec_())
